import { Inter } from "next/font/google";
import { AuthProvider } from "../context/useAuth";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { TeamProvider } from "@/context/useTeam";
import { DataProvider } from "@/context/useData";
import { TeamDataProvider } from "@/context/userTeamData";
import { TeamModalProvider } from "@/context/useTeamModal";
import { TeamInvitationProvider } from "@/context/useInviteModal";
import { DeleteteModalProvider } from "@/context/useDeleteModal";
import { TeamParamProvider } from "@/context/useTeamParams";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FileDrive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <TeamProvider>
            <DataProvider>
              <TeamDataProvider>
                <TeamInvitationProvider>
                  <TeamModalProvider>
                    <DeleteteModalProvider>
                      <TeamParamProvider>
                      {children}
                      </TeamParamProvider>
                      </DeleteteModalProvider>
                  </TeamModalProvider>
                </TeamInvitationProvider>
              </TeamDataProvider>
            </DataProvider>
          </TeamProvider>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
